theme: jekyll-theme-time-machine
title: Mac Cutler, a Comp Math Odyssey
description: Welcome to my personal journey of mastering the field of computational mathematics. Enjoy the ride, and I guess take a look at the homework too.
markdown: kramdown
